apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanboard
  namespace: web
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "75m"
    nginx.org/client-max-body-size: "75m"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: tm-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - kanboard.playmonumenta.com
  rules:
    - host: kanboard.playmonumenta.com
      http:
        paths:
         - pathType: Prefix
           path: "/"
           backend:
             service:
               name: kanboard
               port:
                 number: 80

---

# Service / network ports

apiVersion: v1
kind: Service
metadata:
  name: kanboard
  namespace: web
  labels:
    app: kanboard
spec:
  type: ClusterIP
  selector:
    app: kanboard
  ports:
  - name: "80"
    port: 80
    targetPort: 80

---

# PHP increase memory

apiVersion: v1
kind: ConfigMap
metadata:
  name: kanboard-php-config
  namespace: web
data:
  kanboard-memory.ini: |
    memory_limit = 768M

---

# Main config file

apiVersion: v1
kind: ConfigMap
metadata:
  name: kanboard-config
  namespace: web
data:
  config.php: |
    <?php

    // Enable/Disable debug
    define('DEBUG', false);

    // Available log drivers: syslog, stderr, stdout, system or file
    define('LOG_DRIVER', 'system');

    // Enable/disable email configuration from the user interface
    define('MAIL_CONFIGURATION', false);

    // Enable or disable "Strict-Transport-Security" HTTP header
    define('ENABLE_HSTS', false);

    // Enable/disable url rewrite
    define('ENABLE_URL_REWRITE', false);

    // Enable captcha after 3 authentication failure
    define('BRUTEFORCE_CAPTCHA', 10);

    // Lock the account after 6 authentication failure
    define('BRUTEFORCE_LOCKDOWN', 20);

    // Lock account duration in minute
    define('BRUTEFORCE_LOCKDOWN_DURATION', 15);

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
  namespace: web
  labels:
    app: kanboard
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      labels:
        app: kanboard
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-17
      volumes:
        - name: kanboard-php-config
          configMap:
            name: kanboard-php-config
        - name: kanboard-config
          configMap:
            name: kanboard-config
        - name: kanboard-data
          hostPath:
            type: Directory
            path: /nfs/kanboard/data
        - name: kanboard-plugins
          hostPath:
            type: Directory
            path: /nfs/kanboard/plugins
        - name: kanboard-ssl
          hostPath:
            type: Directory
            path: /nfs/kanboard/ssl
      containers:
      - name: kanboard
        image: kanboard/kanboard:v1.2.18
        tty: false
        stdin: false
        volumeMounts:
        - name: kanboard-config
          mountPath: /var/www/app/config.php
          subPath: config.php
        - name: kanboard-php-config
          mountPath: /etc/php7/conf.d/kanboard-memory.ini
          subPath: kanboard-memory.ini
        - name: kanboard-data
          mountPath: /var/www/app/data
        - name: kanboard-plugins
          mountPath: /var/www/app/plugins
        - name: kanboard-ssl
          mountPath: /etc/nginx/ssl
        resources:
          limits:
            cpu: 250m
            memory: 768Mi
            hugepages-2Mi: 256Mi
          requests:
            cpu: 100m
            memory: 512Mi
            hugepages-2Mi: 256Mi
