
# NOTE: This depends on the service account stuff already existing that's set up by automation-bot.yaml
# This is just the deployment for the 2nd bot

# Service / internal network ports (for loading play data)

apiVersion: v1
kind: Service
metadata:
  name: automation-bot-m18
  namespace: volt
  labels:
    app: automation-bot-m18
spec:
  selector:
    app: automation-bot-m18
  ports:
  - name: volt1
    port: 1111
    targetPort: 1111
  - name: volt2
    port: 1112
    targetPort: 1112
  - name: volt3
    port: 1113
    targetPort: 1113
  - name: volt4
    port: 1114
    targetPort: 1114
  - name: volt5
    port: 1115
    targetPort: 1115

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-bot-m18
  namespace: volt
  labels:
    app: automation-bot-m18
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: automation-bot-m18
  template:
    metadata:
      labels:
        app: automation-bot-m18
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-18
      serviceAccountName: automation-bot-service-account
      volumes:
        - name: nfs-data
          hostPath:
            type: Directory
            path: /nfs/volt/m18
        - name: nfs-redis
          hostPath:
            type: Directory
            path: /nfs/volt/redis
        - name: nfs-domain-shared
          hostPath:
            type: Directory
            path: /nfs/3_DOMAIN_SHARED/volt
        - name: nfs-shared
          hostPath:
            type: Directory
            path: /nfs/4_SHARED
        - name: nfs-scratch
          hostPath:
            type: Directory
            path: /nfs/5_SCRATCH
        - name: secret-config
          secret:
            secretName: automation-bot-m18-config
      containers:
      - name: automation-bot
        image: ghcr.io/teammonumenta/monumenta-automation/monumenta-automation-bot-volt
        tty: false
        stdin: false
        ports:
        - containerPort: 1111
        - containerPort: 1112
        - containerPort: 1113
        - containerPort: 1114
        - containerPort: 1115
        env:
          # This is the root password in a convenient environment variable so it can be used to copy the mysql
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - name: nfs-data
          mountPath: /home/epic/volt/m18
        - name: nfs-redis
          mountPath: /home/epic/volt/redis
          # XXX NOTE
          # 1_ARCHIVE is deliberately not mounted into stage/volt automation bot
          # This is because part of running weekly test updates there is generating backup files
          # and currently those backups would overwrite play server backups made on the same day
          # If you change this to mount in 1_ARCHIVE, you must change the weekly update script as well
        - name: nfs-domain-shared
          mountPath: /home/epic/3_DOMAIN_SHARED
        - name: nfs-shared
          mountPath: /home/epic/4_SHARED
        - name: nfs-scratch
          mountPath: /home/epic/5_SCRATCH
        - name: secret-config
          mountPath: /home/epic/.monumenta_bot
        resources:
          requests:
            cpu: "0"
          limits:
            cpu: "12"
