#!/usr/bin/python3

import os

allowedTypes = (
    ".json",
)

foldersToWalk = [
    "/home/rock/project_epic/region_1/Project_Epic-region_1/advancements/",
]

allRenamed = (
    ("monumenta:challenges/r1/acrobat/all","monumenta:acrobat/r1/all"),
    ("monumenta:challenges/r1/acrobat/farr/shops","monumenta:acrobat/r1/farr/shops"),
    ("monumenta:challenges/r1/acrobat/highwatch/bathhouse","monumenta:acrobat/r1/highwatch/bathhouse"),
    ("monumenta:challenges/r1/acrobat/highwatch/castle","monumenta:acrobat/r1/highwatch/castle"),
    ("monumenta:challenges/r1/acrobat/highwatch/monument","monumenta:acrobat/r1/highwatch/monument"),
    ("monumenta:challenges/r1/acrobat/lowtide/library_tower","monumenta:acrobat/r1/lowtide/library_tower"),
    ("monumenta:challenges/r1/acrobat/lowtide/ship","monumenta:acrobat/r1/lowtide/ship"),
    ("monumenta:challenges/r1/acrobat/nyr/armory","monumenta:acrobat/r1/nyr/armory"),
    ("monumenta:challenges/r1/acrobat/nyr/windmill","monumenta:acrobat/r1/nyr/windmill"),
    ("monumenta:challenges/r1/acrobat/reverie/lobby","monumenta:acrobat/r1/reverie/lobby"),
    ("monumenta:challenges/r1/acrobat/sierhaven/apartments","monumenta:acrobat/r1/sierhaven/apartments"),
    ("monumenta:challenges/r1/acrobat/sierhaven/flag","monumenta:acrobat/r1/sierhaven/flag"),
    ("monumenta:challenges/r1/acrobat/sierhaven/royal","monumenta:acrobat/r1/sierhaven/royal"),
    ("monumenta:challenges/r1/acrobat/sierhaven/tree","monumenta:acrobat/r1/sierhaven/tree"),
    ("monumenta:challenges/r1/acrobat/taeldim/spring","monumenta:acrobat/r1/taeldim/spring"),
    ("monumenta:guide/root","monumenta:handbook/root"),
    ("monumenta:guide/armor_category/root","monumenta:handbook/armor_category/root"),
    ("monumenta:guide/armor_category/cloth","monumenta:handbook/armor_category/cloth"),
    ("monumenta:guide/armor_category/leather","monumenta:handbook/armor_category/leather"),
    ("monumenta:guide/enchantments/root","monumenta:handbook/enchantments/root"),
    ("monumenta:guide/enchantments/chaotic","monumenta:handbook/enchantments/chaotic"),
    ("monumenta:guide/enchantments/curse_of_corruption","monumenta:handbook/enchantments/corruption"),
    ("monumenta:guide/enchantments/darksight","monumenta:handbook/enchantments/darksight"),
    ("monumenta:guide/enchantments/gilded","monumenta:handbook/enchantments/gilded"),
    ("monumenta:guide/enchantments/gills","monumenta:handbook/enchantments/gills"),
    ("monumenta:guide/enchantments/hope","monumenta:handbook/enchantments/hope"),
    ("monumenta:guide/enchantments/mainhand_regeneration","monumenta:handbook/enchantments/mainhand_regeneration"),
    ("monumenta:guide/enchantments/radiant","monumenta:handbook/enchantments/radiant"),
    ("monumenta:guide/enchantments/regeneration","monumenta:handbook/enchantments/regeneration"),
    ("monumenta:guide/enchantments/unbreaking","monumenta:handbook/enchantments/unbreaking"),
    ("monumenta:guide/important_sites/root","monumenta:handbook/important_sites/r1/root"),
    ("monumenta:guide/important_sites/academy","monumenta:handbook/important_sites/r1/academy"),
    ("monumenta:guide/important_sites/apartment","monumenta:handbook/important_sites/r1/apartment"),
    ("monumenta:guide/important_sites/casino","monumenta:handbook/important_sites/r1/casino"),
    ("monumenta:guide/important_sites/castle","monumenta:handbook/important_sites/r1/castle"),
    ("monumenta:guide/important_sites/circus","monumenta:handbook/important_sites/r1/circus"),
    ("monumenta:guide/important_sites/city_guide","monumenta:handbook/important_sites/r1/city_guide"),
    ("monumenta:guide/important_sites/crafter","monumenta:handbook/important_sites/r1/crafter"),
    ("monumenta:guide/important_sites/herald","monumenta:handbook/important_sites/r1/herald"),
    ("monumenta:guide/important_sites/monument","monumenta:handbook/important_sites/r1/monument"),
    ("monumenta:guide/important_sites/patron_shrine","monumenta:handbook/important_sites/r1/patron_shrine"),
    ("monumenta:guide/important_sites/teleport_hub","monumenta:handbook/important_sites/r1/teleport_hub"),
    ("monumenta:guide/important_sites/transmog","monumenta:handbook/important_sites/r1/transmog"),
    ("monumenta:guide/mobs/root","monumenta:handbook/mobs/root"),
    ("monumenta:guide/mobs/elites","monumenta:handbook/mobs/elites"),
    ("monumenta:guide/mobs/player_death","monumenta:handbook/mobs/player_death"),
    ("monumenta:guide/money/root","monumenta:handbook/money/root"),
    ("monumenta:guide/money/ac","monumenta:handbook/money/ac"),
    ("monumenta:guide/money/chip","monumenta:handbook/money/chip"),
    ("monumenta:guide/money/cxp","monumenta:handbook/money/cxp"),
    ("monumenta:guide/money/pd","monumenta:handbook/money/pd"),
    ("monumenta:guide/money/rc","monumenta:handbook/money/rc"),
    ("monumenta:guide/money/xp","monumenta:handbook/money/xp"),
    ("monumenta:quests/r1/WUHL","monumenta:quests/r1/wuhl"),
    ("monumenta:dungeons","monumenta:dungeons/root"),
    ("dungeons:white/find_quest","monumenta:dungeons/white/find_quest"),
    ("dungeons:white/find","monumenta:dungeons/white/find"),
    ("dungeons:white/complete","monumenta:dungeons/white/complete"),
    ("dungeons:orange/find_quest","monumenta:dungeons/orange/find_quest"),
    ("dungeons:orange/find","monumenta:dungeons/orange/find"),
    ("dungeons:orange/complete","monumenta:dungeons/orange/complete"),
    ("dungeons:magenta/find_quest","monumenta:dungeons/magenta/find_quest"),
    ("dungeons:magenta/find","monumenta:dungeons/magenta/find"),
    ("dungeons:magenta/complete","monumenta:dungeons/magenta/complete"),
    ("dungeons:light_blue/find","monumenta:dungeons/light_blue/find"),
    ("dungeons:light_blue/complete","monumenta:dungeons/light_blue/complete"),
    ("dungeons:yellow/find","monumenta:dungeons/yellow/find"),
    ("dungeons:yellow/complete","monumenta:dungeons/yellow/complete"),
    ("monumenta:quests/r1/thestaff","monumenta:dungeons/r1bonus/find_quest"),
    ("dungeons:r1bonus/find","monumenta:dungeons/r1bonus/find"),
    ("dungeons:r1bonus/complete","monumenta:dungeons/r1bonus/complete"),
    ("pois:root","monumenta:pois/r1/root"),
    ("pois:highlands","monumenta:pois/r1/highlands/root"),
    ("pois:jungle","monumenta:pois/r1/jungle/root"),
    ("pois:swamp","monumenta:pois/r1/swamp/root"),
    ("monumenta:general/highlanddiscover","monumenta:pois/r1/highlands/discover"),
    ("monumenta:general/junglediscover","monumenta:pois/r1/jungle/discover"),
    ("monumenta:general/swampdiscover","monumenta:pois/r1/swamp/discover"),
    ("pois:anthill","monumenta:pois/r1/highlands/anthill"),
    ("pois:caveofbones","monumenta:pois/r1/highlands/caveofbones"),
    ("pois:cursedforest","monumenta:pois/r1/highlands/cursedforest"),
    ("pois:easternpass","monumenta:pois/r1/highlands/easternpass"),
    ("pois:graveyard","monumenta:pois/r1/highlands/graveyard"),
    ("pois:infestedhouse","monumenta:pois/r1/highlands/infestedhouse"),
    ("pois:verdantfortress","monumenta:pois/r1/highlands/verdantfortress"),
    ("pois:volcano","monumenta:pois/r1/highlands/volcano"),
    ("pois:centralplateau","monumenta:pois/r1/jungle/center/root"),
    ("pois:mountains","monumenta:pois/r1/jungle/mountains/root"),
    ("pois:northeastjungle","monumenta:pois/r1/jungle/northeast/root"),
    ("pois:northwestjungle","monumenta:pois/r1/jungle/northwest/root"),
    ("pois:southeastjungle","monumenta:pois/r1/jungle/southeast/root"),
    ("pois:southwestjungle","monumenta:pois/r1/jungle/southwest/root"),
    ("pois:airshrine","monumenta:pois/r1/jungle/center/airshrine"),
    ("pois:grandmaw","monumenta:pois/r1/jungle/center/grandmaw"),
    ("pois:hawkfortress","monumenta:pois/r1/jungle/center/hawkfortress"),
    ("pois:axtanmonastary","monumenta:pois/r1/jungle/mountains/axtanmonastary"),
    ("pois:collapsingtower","monumenta:pois/r1/jungle/mountains/collapsingtower"),
    ("pois:creeperfarm","monumenta:pois/r1/jungle/mountains/creeperfarm"),
    ("pois:firecave","monumenta:pois/r1/jungle/mountains/firecave"),
    ("pois:mountainhideaway","monumenta:pois/r1/jungle/mountains/mountainhideaway"),
    ("pois:mountainmines","monumenta:pois/r1/jungle/mountains/mountainmines"),
    ("pois:caveofsecrets","monumenta:pois/r1/jungle/northeast/caveofsecrets"),
    ("pois:crossroadruins","monumenta:pois/r1/jungle/northeast/crossroadruins"),
    ("pois:junglemine","monumenta:pois/r1/jungle/northeast/junglemine"),
    ("pois:litterbox","monumenta:pois/r1/jungle/northeast/litterbox"),
    ("pois:moistruins","monumenta:pois/r1/jungle/northeast/moistruins"),
    ("pois:moltenchasm","monumenta:pois/r1/jungle/northeast/moltenchasm"),
    ("pois:suspiciousvillage","monumenta:pois/r1/jungle/northeast/suspiciousvillage"),
    ("pois:tinyjungleruin","monumenta:pois/r1/jungle/northeast/tinyjungleruin"),
    ("pois:ancientruin","monumenta:pois/r1/jungle/northwest/ancientruin"),
    ("pois:hawkvillage","monumenta:pois/r1/jungle/northwest/hawkvillage"),
    ("pois:murkymaze","monumenta:pois/r1/jungle/northwest/murkymaze"),
    ("pois:mysteriouscenote","monumenta:pois/r1/jungle/northwest/mysteriouscenote"),
    ("pois:northjaguar","monumenta:pois/r1/jungle/northwest/northjaguar"),
    ("pois:overgrowncave","monumenta:pois/r1/jungle/northwest/overgrowncave"),
    ("pois:ruinedmansion","monumenta:pois/r1/jungle/northwest/ruinedmansion"),
    ("pois:watercavern","monumenta:pois/r1/jungle/northwest/watercavern"),
    ("pois:white","monumenta:pois/r1/jungle/northwest/tlaxanziggurat"),
    ("pois:corruptedcaves","monumenta:pois/r1/jungle/southeast/corruptedcaves"),
    ("pois:corruptedisland","monumenta:pois/r1/jungle/southeast/corruptedisland"),
    ("pois:creepertower","monumenta:pois/r1/jungle/southeast/creepertower"),
    ("pois:hallowedpond","monumenta:pois/r1/jungle/southeast/hallowedpond"),
    ("pois:lowlandtemple","monumenta:pois/r1/jungle/southeast/lowlandtemple"),
    ("pois:southerncenote","monumenta:pois/r1/jungle/southeast/southerncenote"),
    ("pois:eastswamp","monumenta:pois/r1/swamp/east/root"),
    ("pois:northswamp","monumenta:pois/r1/swamp/north/root"),
    ("pois:westswamp","monumenta:pois/r1/swamp/south/root"),
    ("pois:easternmine","monumenta:pois/r1/swamp/east/easternmine"),
    ("pois:fireshrine","monumenta:pois/r1/swamp/east/fireshrine"),
    ("pois:fishinghuts","monumenta:pois/r1/swamp/east/fishinghuts"),
    ("pois:ruineddocks","monumenta:pois/r1/swamp/east/ruineddocks"),
    ("pois:watershrine","monumenta:pois/r1/swamp/east/watershrine"),
    ("pois:banditcamp","monumenta:pois/r1/swamp/north/banditcamp"),
    ("pois:banditstronghold","monumenta:pois/r1/swamp/north/banditstronghold"),
    ("pois:magetower","monumenta:pois/r1/swamp/north/magetower"),
    ("pois:mercenarycamp","monumenta:pois/r1/swamp/north/mercenarycamp"),
    ("pois:northmine","monumenta:pois/r1/swamp/north/northmine"),
    ("pois:sinkhole","monumenta:pois/r1/swamp/north/sinkhole"),
    ("pois:waterfallisland","monumenta:pois/r1/swamp/north/waterfallisland"),
    ("pois:hauntedmine","monumenta:pois/r1/swamp/south/hauntedmine"),
    ("pois:lighthouse","monumenta:pois/r1/swamp/south/lighthouse"),
    ("pois:southeasternmineshaft","monumenta:pois/r1/swamp/south/southeasternmine"),
    ("pois:southernmineshaft","monumenta:pois/r1/swamp/south/southernmine"),
    ("pois:southernvillage","monumenta:pois/r1/swamp/south/southernvillage"),
    ("pois:witchvillage","monumenta:pois/r1/swamp/south/witchvillage"),
    ("slayer:root","monumenta:slayer_legacy/root"),
    ("slayer:bslayer1","monumenta:slayer_legacy/bslayer1"),
    ("slayer:bslayer2","monumenta:slayer_legacy/bslayer2"),
    ("slayer:bslayer3","monumenta:slayer_legacy/bslayer3"),
    ("slayer:bslayer4","monumenta:slayer_legacy/bslayer4"),
    ("slayer:bslayer5","monumenta:slayer_legacy/bslayer5"),
    ("slayer:cslayer1","monumenta:slayer_legacy/cslayer1"),
    ("slayer:cslayer2","monumenta:slayer_legacy/cslayer2"),
    ("slayer:cslayer3","monumenta:slayer_legacy/cslayer3"),
    ("slayer:cslayer4","monumenta:slayer_legacy/cslayer4"),
    ("slayer:cslayer5","monumenta:slayer_legacy/cslayer5"),
    ("slayer:spislayer1","monumenta:slayer_legacy/spislayer1"),
    ("slayer:spislayer2","monumenta:slayer_legacy/spislayer2"),
    ("slayer:spislayer3","monumenta:slayer_legacy/spislayer3"),
    ("slayer:spislayer4","monumenta:slayer_legacy/spislayer4"),
    ("slayer:spislayer5","monumenta:slayer_legacy/spislayer5"),
    ("slayer:sslayer1","monumenta:slayer_legacy/sslayer1"),
    ("slayer:sslayer2","monumenta:slayer_legacy/sslayer2"),
    ("slayer:sslayer3","monumenta:slayer_legacy/sslayer3"),
    ("slayer:sslayer4","monumenta:slayer_legacy/sslayer4"),
    ("slayer:sslayer5","monumenta:slayer_legacy/sslayer5"),
    ("slayer:zslayer1","monumenta:slayer_legacy/zslayer1"),
    ("slayer:zslayer2","monumenta:slayer_legacy/zslayer2"),
    ("slayer:zslayer3","monumenta:slayer_legacy/zslayer3"),
    ("slayer:zslayer4","monumenta:slayer_legacy/zslayer4"),
    ("slayer:zslayer5","monumenta:slayer_legacy/zslayer5"),
    ("monumenta:challenges/speedruns/r1/tutorial","monumenta:speedster/r1/tutorial"),
    ("monumenta:challenges/speedruns/r1/all","monumenta:speedster/r1/all"),
    ("monumenta:challenges/speedruns/r1/high_to_low/3","monumenta:speedster/r1/high_to_low/3"),
    ("monumenta:challenges/speedruns/r1/high_to_low/2","monumenta:speedster/r1/high_to_low/2"),
    ("monumenta:challenges/speedruns/r1/high_to_low/1","monumenta:speedster/r1/high_to_low/1"),
    ("monumenta:challenges/speedruns/r1/high_to_low/0","monumenta:speedster/r1/high_to_low/0"),
    ("monumenta:challenges/speedruns/r1/mariya's_game/3","monumenta:speedster/r1/mariyas_game/3"),
    ("monumenta:challenges/speedruns/r1/mariya's_game/2","monumenta:speedster/r1/mariyas_game/2"),
    ("monumenta:challenges/speedruns/r1/mariya's_game/1","monumenta:speedster/r1/mariyas_game/1"),
    ("monumenta:challenges/speedruns/r1/mariya's_game/0","monumenta:speedster/r1/mariyas_game/0"),
    ("monumenta:challenges/speedruns/r1/tree_hopping_madness/3","monumenta:speedster/r1/tree_hopping_madness/3"),
    ("monumenta:challenges/speedruns/r1/tree_hopping_madness/2","monumenta:speedster/r1/tree_hopping_madness/2"),
    ("monumenta:challenges/speedruns/r1/tree_hopping_madness/1","monumenta:speedster/r1/tree_hopping_madness/1"),
    ("monumenta:challenges/speedruns/r1/tree_hopping_madness/0","monumenta:speedster/r1/tree_hopping_madness/0"),
    ("monumenta:challenges/speedruns/r1/tutorial+/3","monumenta:speedster/r1/tutorial_plus/3"),
    ("monumenta:challenges/speedruns/r1/tutorial+/2","monumenta:speedster/r1/tutorial_plus/2"),
    ("monumenta:challenges/speedruns/r1/tutorial+/1","monumenta:speedster/r1/tutorial_plus/1"),
    ("monumenta:challenges/speedruns/r1/tutorial+/0","monumenta:speedster/r1/tutorial_plus/0"),
    ("monumenta:events/2018","monumenta:trophies/events/2018"),
    ("monumenta:events/2018/knuckles","monumenta:trophies/events/2018/knuckles"),
    ("monumenta:events/2018/valentines","monumenta:trophies/events/2018/valentines"),
    ("achievements:root","monumenta:general/root"),
    ("achievements:ourlordandsavior","monumenta:general/ourlordandsavior"),
    ("achievements:immortal","monumenta:general/immortal"),
    ("achievements:fisherman1","monumenta:general/fisherman1"),
    ("achievements:fisherman2","monumenta:general/fisherman2"),
    ("achievements:fisherman3","monumenta:general/fisherman3"),
    ("achievements:fisherman4","monumenta:general/fisherman4"),
    ("achievements:fisherman5","monumenta:general/fisherman5"),
    ("achievements:gluttony1","monumenta:general/gluttony1"),
    ("achievements:gluttony2","monumenta:general/gluttony2"),
    ("achievements:gluttony3","monumenta:general/gluttony3"),
    ("achievements:gluttony4","monumenta:general/gluttony4"),
    ("achievements:gluttony5","monumenta:general/gluttony5"),
    ("achievements:repair1","monumenta:general/repair1"),
    ("achievements:repair2","monumenta:general/repair2"),
    ("achievements:repair3","monumenta:general/repair3"),
    ("achievements:repair4","monumenta:general/repair4"),
    ("achievements:repair5","monumenta:general/repair5"),
    ("achievements:transmog1","monumenta:general/transmog1"),
    ("achievements:transmog2","monumenta:general/transmog2"),
    ("achievements:transmog3","monumenta:general/transmog3"),
    ("achievements:transmog4","monumenta:general/transmog4"),
    ("achievements:transmog5","monumenta:general/transmog5"),
    ("monumenta:trigger/player_killed_entity/r1/elite/ancient%20guardian","monumenta:trigger/player_killed_entity/region_1/elite/ancient_guardian"),
    ("monumenta:trigger/player_killed_entity/region_1/elite/ancient%20guardian","monumenta:trigger/player_killed_entity/region_1/elite/ancient_guardian"),
    ("achievements:junglediscover","monumenta:pois/r1/jungle/discover"),
    ("achievements:highlanddiscover","monumenta:pois/r1/highlands/discover"),
    ("dungeons:root","monumenta:dungeons/root"),
    ("achievements:fisherman5","monumenta:general/fisherman5"),
    ("pois:southswamp","monumenta:pois/r1/swamp/south/root"),
    ("pois:southjaguar","monumenta:pois/r1/jungle/southwest/southjaguar"),
    ("achievements:swampdiscover","monumenta:pois/r1/swamp/discover"),
    ("pois:spookyforest","monumenta:pois/r1/highlands/cursedforest"),
    ("pois:earthshrine","monumenta:pois/r1/jungle/southwest/earthshrine"),
    ("pois:firemine","monumenta:pois/r1/jungle/southwest/abandonedtunnels"),
    ("pois:abandonedtunnels","monumenta:pois/r1/jungle/southwest/abandonedtunnels"),
    ("pois:serpentruins","monumenta:pois/r1/jungle/southwest/serpentruins"),
    ("pois:abandonedmansion","monumenta:pois/r1/jungle/northwest/ruinedmansion"),
    ("pois:westbandit","monumenta:pois/r1/swamp/north/banditstronghold"),
    ("monumenta:wuhl","monumenta:quests/r1/wuhl"),
    ("monumenta:slayer/root","monumenta:slayer_legacy/root"),
    ("monumenta:igor/1","monumenta:general/igor/1"),
    ("monumenta:igor/2","monumenta:general/igor/2"),
    ("monumenta:igor/3","monumenta:general/igor/3"),
    ("monumenta:igor/4","monumenta:general/igor/4"),
    ("monumenta:igor/5","monumenta:general/igor/5"),
    ("monumenta:seasonal_events/2017","monumenta:trophies/events/2017/root"),
    ("monumenta:seasonal_events/2017/halloween","monumenta:trophies/events/2017/halloween"),
    ("monumenta:seasonal_events/2017/winter","monumenta:trophies/events/2017/winter"),

    ("monumenta:challenges/speedruns/r1/mariya\\u0027s_game/0","monumenta:speedster/r1/mariyas_game/0"),
    ("monumenta:challenges/speedruns/r1/mariya\\u0027s_game/1","monumenta:speedster/r1/mariyas_game/1"),
    ("monumenta:challenges/speedruns/r1/mariya\\u0027s_game/2","monumenta:speedster/r1/mariyas_game/2"),
    ("monumenta:challenges/speedruns/r1/mariya\\u0027s_game/3","monumenta:speedster/r1/mariyas_game/3"),
)

def fix_file(filePath,allRenamed):
    try:
        test = open(filePath, "r")
        test.close()
        os.rename( filePath, filePath + ".old" )
        with open(filePath + ".old", "r") as fin:
            with open(filePath, "w") as fout:
                for line in fin:
                    for renamed in allRenamed:
                        line = line.replace( '"' + renamed[0] + '"', '"' + renamed[1] + '"' )
                    fout.write(line)
                fout.close()
            fin.close()
        os.remove(filePath + ".old")
    except:
        pass

for aFolderToWalk in foldersToWalk:
    for folderInfo in os.walk(aFolderToWalk):
        folder=folderInfo[0]
        files =folderInfo[2]
        for fileName in files:
            for aType in allowedTypes:
                if fileName[-len(aType):] == aType:
                    filePath = folder+'/'+fileName
                    print(filePath)
                    fix_file( filePath, allRenamed )

