#
# NOTE:
# To generate the maps-auth secret, run these commands:
# htpasswd -c ./auth plan
# kubectl create secret generic plan-auth --from-file auth -n play
# rm auth
#
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: plan
  namespace: play
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: plan-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
spec:
  tls:
  - hosts:
    - plan.playmonumenta.com
  rules:
  - host: plan.playmonumenta.com
    http:
      paths:
      - backend:
          serviceName: bungee
          servicePort: 8804

---

# Service / internal network ports

apiVersion: v1
kind: Service
metadata:
  name: bungee
  namespace: play
  labels:
    app: bungee
spec:
  type: ClusterIP
  selector:
    app: bungee
  ports:
  # Socket4MC
  - name: "9575"
    port: 9575
    targetPort: 9575
  # Plan
  - name: "8804"
    port: 8804
    targetPort: 8804

---

# Service / external network ports

apiVersion: v1
kind: Service
metadata:
  name: bungee-nodeport
  namespace: play
  labels:
    app: bungee
spec:
  type: NodePort
  #externalTrafficPolicy: Local
  selector:
    app: bungee
  ports:
  # Main minecraft port
  - name: "25565"
    port: 25565
    nodePort: 25565
    targetPort: 25565

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungee
  namespace: play
  labels:
    app: bungee
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bungee
  template:
    metadata:
      labels:
        app: bungee
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ns547336.ip-66-70-181.net
      volumes:
        - name: nfs-volume
          hostPath:
            path: /nfs/play/project_epic
            type: Directory
      containers:
      - name: bungee
        image: monumenta-docker.injic.io/monumenta-java-shard
        tty: true
        stdin: true
        ports:
        - containerPort: 25565
        - containerPort: 9575
        - containerPort: 8804
        env:
        - name: "JAVA_MEM"
          value: "4G"
        - name: "JAVA_META_MEM"
          value: "256M"
        - name: "JAVA_JAR"
          value: "BungeeCord.jar"
        - name: "SERVER_DIR"
          value: "/project_epic/bungee"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
        readinessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: nfs-volume
          mountPath: /project_epic
        resources:
          limits:
            memory: 1Gi
            hugepages-2Mi: 4608Mi
          requests:
            memory: 64Mi
            hugepages-2Mi: 4608Mi
      imagePullSecrets:
      - name: regcred
