# Service / network ports

apiVersion: v1
kind: Service
metadata:
  name: purgatory
  namespace: play
  labels:
    app: purgatory
spec:
  type: ClusterIP
  selector:
    app: purgatory
  ports:
  # Main minecraft port
  - name: "25566"
    port: 25566
    targetPort: 25566

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: purgatory
  namespace: play
  labels:
    app: purgatory
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: purgatory
  template:
    metadata:
      labels:
        app: purgatory
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-9
      volumes:
        - name: nfs-volume
          hostPath:
            type: Directory
            path: /nfs/play/project_epic
      containers:
      - name: purgatory
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-java-shard
        tty: true
        stdin: true
        ports:
        - containerPort: 25566
        env:
        # Set this to however much RAM the shard needs
        - name: "JAVA_MEM"
          value: "1024M"
        # Set this to 256M regardless of JAVA_MEM
        - name: "JAVA_META_MEM"
          value: "256M"
        - name: "JAVA_JAR"
          value: "paperclip.jar"
        - name: "SERVER_DIR"
          value: "/project_epic/purgatory"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
        readinessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: nfs-volume
          mountPath: /project_epic
        resources:
          limits:
            # Set this to 1Gi
            # This is the hard limit for how much RAM a shard can allocate beyond what it needs for hugepages
            # It should not need much/any...
            memory: 1Gi
            # Set this to JAVA_MEM + JAVA_META_MEM + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: 1344Mi
          requests:
            # Set this to 64Mi
            # The shard should not need non-hugepage RAM by default
            memory: 64Mi
            # Set this to JAVA_MEM + JAVA_META_MEM + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: 1344Mi
      imagePullSecrets:
      - name: githubcred
