# Service / network ports

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
{{- if .Values.fastMetrics }}
    k8s-app: monumenta-metrics-fast
{{- else }}
    k8s-app: monumenta-metrics
{{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
  # Main minecraft port
  - name: "25566"
    port: 25566
    targetPort: 25566
  - name: metrics
    port: 9225
    targetPort: 9225

{{- if .Values.nodePort }}
---

# Service / external network ports

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
  # Main minecraft port
  - name: "25566"
    port: {{ .Values.nodePort }}
    nodePort: {{ .Values.nodePort }}
    targetPort: 25566
{{- end }}

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodeFull }}
      volumes:
{{- if .Values.gsheetCredentials }}
        - name: gsheet-credentials
          secret:
            secretName: gsheet-credentials
            defaultMode: 0444
{{- end }}
        - name: nfs-maps
          hostPath:
            path: /nfs/{{ .Values.namespace }}/maps
            type: Directory
        - name: nfs-project-epic
          hostPath:
            path: /nfs/{{ .Values.namespace }}/{{ .Values.node }}
            type: Directory
        - name: nfs-shared
          hostPath:
            path: /nfs/4_SHARED
            type: Directory
      terminationGracePeriodSeconds: 90
      containers:
      - name: {{ .Values.name }}
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-java-shard
        tty: true
        stdin: true
        ports:
        - containerPort: 25566
        - containerPort: 8000
        - containerPort: 9225
        env:
        # Set this to however much RAM the shard needs
        - name: "JAVA_MEM"
          value: "{{ .Values.memMB }}M"
        # Set this to 256M regardless of JAVA_MEM
        - name: "JAVA_META_MEM"
          value: "256M"
        - name: "JAVA_JAR"
          value: "paperclip.jar"
        - name: "SERVER_DIR"
          value: "/home/epic/{{ .Values.namespace }}/{{ .Values.node }}/{{ .Values.name }}"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
{{- if .Values.useHTTPForProbes }}
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /alive
            port: 8000
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
{{- else if .Values.useSocketForProbes }}
        readinessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
{{- end }}
        volumeMounts:
        - name: nfs-project-epic
          mountPath: /home/epic/{{ .Values.namespace }}/{{ .Values.node }}
{{- if .Values.gsheetCredentials }}
        - name: gsheet-credentials
          mountPath: /home/epic/{{ .Values.namespace }}/{{ .Values.node }}/{{ .Values.name }}/plugins/ScriptedQuests/gsheet_credentials.json
          subPath: gsheet_credentials.json
{{- end }}
        - name: nfs-maps
          mountPath: /home/epic/maps/dynmap/{{ .Values.namespace }}
        - name: nfs-shared
          mountPath: /home/epic/4_SHARED
        resources:
          limits:
            # Set this to 1Gi
            # This is the hard limit for how much RAM a shard can allocate beyond what it needs for hugepages
            # It should not need much/any...
            memory: 1Gi
            # Set this to JAVA_MEM + 32 + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: {{ add .Values.memMB (div .Values.memMB 16) 32 }}Mi
          requests:
            # Set this to 64Mi
            # The shard should not need non-hugepage RAM by default
            memory: 64Mi
            # Set this to JAVA_MEM + 32 + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: {{ add .Values.memMB (div .Values.memMB 16) 32 }}Mi
      imagePullSecrets:
      - name: githubcred
