# Service / network ports

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
{{- if .Values.fastMetrics }}
    k8s-app: monumenta-metrics-fast
{{- else }}
    k8s-app: monumenta-metrics
{{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
  # Main minecraft port
  - name: "25566"
    port: 25566
    targetPort: 25566
  - name: metrics
    port: 9225
    targetPort: 9225
{{- if eq .Values.namespace "build" }}
  - name: jdb
    port: 9000
    targetPort: 9000
{{- end }}

{{- if .Values.nodePort }}
---

# Service / external network ports

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
  # Main minecraft port
  - name: "25566"
    port: {{ .Values.nodePort }}
    nodePort: {{ .Values.nodePort }}
    targetPort: 25566
{{- end }}

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  strategy:
    type: Recreate
  replicas: 0
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodeFull }}
      volumes:
{{- if .Values.gsheetCredentials }}
        - name: gsheet-credentials
          secret:
            secretName: gsheet-credentials
            defaultMode: 0444
{{- end }}
{{- if .Values.maps }}
        - name: nfs-maps
          hostPath:
            path: /nfs/{{ .Values.namespace }}/maps
            type: Directory
{{- end }}
        - name: nfs-project-epic
          hostPath:
            path: /nfs/{{ .Values.namespace }}/{{ .Values.node }}
            type: Directory
        - name: nfs-domain-shared
          hostPath:
            path: /nfs/3_DOMAIN_SHARED/{{ .Values.namespace }}
            type: Directory
        - name: nfs-shared
          hostPath:
            path: /nfs/4_SHARED
            type: Directory
        - name: nfs-scratch
          hostPath:
            path: /nfs/5_SCRATCH
            type: Directory
      terminationGracePeriodSeconds: 90
      containers:
      - name: {{ .Values.name }}
{{- if eq .Values.name "dev4" }}
        image: "ghcr.io/teammonumenta/monumenta-automation/{{ .Values.imageJbr }}"
{{- else }}
        image: "ghcr.io/teammonumenta/monumenta-automation/{{ .Values.image }}"
{{- end }}
        tty: true
        stdin: true
        ports:
        - containerPort: 25566
        - containerPort: 8000
        - containerPort: 9225
{{- if eq .Values.namespace "build" }}
        - containerPort: 9000
{{- end }}
        env:
        # Set this to however much RAM the shard needs
        - name: "JAVA_MEM"
          value: "{{ .Values.hugePageMB }}M"
        - name: "JAVA_JAR"
          value: "server.jar"
        - name: "SERVER_DIR"
          value: "/home/epic/{{ .Values.namespace }}/{{ .Values.node }}/{{ .Values.name }}"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
        - name: "NETWORK_NAMESPACE"
          value: {{ .Values.namespace }}
        - name: "NETWORK_RELAY_NAME"
          value: {{ .Values.name }}
        - name: "NETWORK_RELAY_SERVER_ADDRESS"
          value: "{{ .Values.name }}:25566"
{{- if eq .Values.name "dev4" }}
        - name: "JAVA_ARG"
          value: "-XX:ActiveProcessorCount={{ .Values.cpuActiveProcessorCount }} -DPaper.IgnoreJavaVersion=true -Ddisable.watchdog -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000 -Dlog4j2.configurationFile=log4j2-shard.xml -XX:+AllowRedefinitionToAddDeleteMethods -XX:+AllowEnhancedClassRedefinition"
{{- else if eq .Values.namespace "build" }}
        - name: "JAVA_ARG"
          value: "-XX:ActiveProcessorCount={{ .Values.cpuActiveProcessorCount }} -DPaper.IgnoreJavaVersion=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000 -Dlog4j2.configurationFile=log4j2-shard.xml"
{{- else if eq .Values.namespace "stage" }}
        - name: "JAVA_ARG"
          value: "-XX:ActiveProcessorCount={{ .Values.cpuActiveProcessorCount }} -DPaper.IgnoreJavaVersion=true -Dlog4j2.configurationFile=log4j2-shard.xml"
{{- else if eq .Values.namespace "volt" }}
        - name: "JAVA_ARG"
          value: "-XX:ActiveProcessorCount={{ .Values.cpuActiveProcessorCount }} -DPaper.IgnoreJavaVersion=true -Dlog4j2.configurationFile=log4j2-shard.xml"
{{- else if eq .Values.namespace "play" }}
        - name: "JAVA_ARG"
          value: "-XX:ActiveProcessorCount={{ .Values.cpuActiveProcessorCount }} -DPaper.IgnoreJavaVersion=true -Dlog4j2.configurationFile=log4j2-shard.xml"
{{- end }}
        - name: "MONUMENTA_IS_PLAY"
{{- if eq .Values.namespace "play" }}
          value: "1"
{{- else if eq .Values.namespace "stage" }}
          value: "1"
{{- else if eq .Values.namespace "volt" }}
          value: "1"
{{- else }}
          value: "0"
{{- end }}
        - name: "MONUMENTA_ENABLE_TIME_WARP"
{{- if eq .Values.namespace "play" }}
          value: "0"
{{- else }}
          value: "1"
{{- end }}
{{- if .Values.useHTTPForProbes }}
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /alive
            port: 8000
          initialDelaySeconds: 360
          timeoutSeconds: 5
          periodSeconds: 10
{{- else if .Values.useSocketForProbes }}
        readinessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 360
          timeoutSeconds: 5
          periodSeconds: 10
{{- end }}
        volumeMounts:
        - name: nfs-project-epic
          mountPath: /home/epic/{{ .Values.namespace }}/{{ .Values.node }}
{{- if .Values.gsheetCredentials }}
        - name: gsheet-credentials
          mountPath: /home/epic/{{ .Values.namespace }}/{{ .Values.node }}/{{ .Values.name }}/plugins/ScriptedQuests/gsheet_credentials.json
          subPath: gsheet_credentials.json
{{- end }}
{{- if .Values.maps }}
{{- if eq .Values.namespace "stage" }}
        - name: nfs-maps
          mountPath: /home/epic/maps/dynmap/play
{{- else if eq .Values.namespace "volt" }}
        - name: nfs-maps
          mountPath: /home/epic/maps/dynmap/play
{{- else }}
        - name: nfs-maps
          mountPath: /home/epic/maps/dynmap/{{ .Values.namespace }}
{{- end }}
{{- end }}
        - name: nfs-domain-shared
          mountPath: /home/epic/3_DOMAIN_SHARED
        - name: nfs-shared
          mountPath: /home/epic/4_SHARED
        - name: nfs-scratch
          mountPath: /home/epic/5_SCRATCH
        resources:
          limits:
            # Set this to 1Gi
            # This is the hard limit for how much RAM a shard can allocate beyond what it needs for hugepages
            # It should not need much/any...
            # TEMP: Set to 4GB to avoid OOMkilling the copy_world on blue
            memory: {{ .Values.memMB }}Mi
            # Set this to JAVA_MEM + 192 + 64 per gigabyte of JAVA_MEM
            # Tried making this 64 extra, low-memory shards still crash with this
            hugepages-2Mi: {{ add .Values.hugePageMB (div .Values.hugePageMB 16) 192 }}Mi
            cpu: {{ .Values.cpuLimits }}
          requests:
            # Set this to 64Mi
            # The shard should not need non-hugepage RAM by default
            memory: 64Mi
            # Tried making this 64 extra, low-memory shards still crash with this
            # Set this to JAVA_MEM + 192 + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: {{ add .Values.hugePageMB (div .Values.hugePageMB 16) 192 }}Mi
            cpu: {{ .Values.cpuReqs }}
