
# Webhook port for kanboard

apiVersion: v1
kind: Service
metadata:
  name: task-bot
spec:
  ports:
  - port: 5000
  selector:
    app: task-bot


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-bot
  labels:
    app: task-bot
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: task-bot
  template:
    metadata:
      labels:
        app: task-bot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-8
      volumes:
        - name: task-bot-storage
          hostPath:
            type: Directory
            path: /nfs/task-bot
      containers:
      - name: task-bot
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-automation-bot
        tty: false
        stdin: false
        volumeMounts:
        - name: task-bot-storage
          mountPath: /home/epic/.task_bot
        command: ["./discord_bots/task_bot/task_bot.py"]
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: githubcred
