# Service / external network ports

apiVersion: v1
kind: Service
metadata:
  name: test-echo-ip
  labels:
    app: test-echo-ip
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: test-echo-ip
  ports:
  - name: minecraft
    port: 80
    nodePort: 9002
    targetPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-echo-ip-config
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        location /remote_addr {
            default_type text/plain;
            return 200 "$remote_addr\n";
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

---

# This is the actual deployment, specifying what it should run
#
# This is just a stock nginx webserver with the appropriate directory mounted
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-echo-ip
  labels:
    app: test-echo-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-echo-ip
  template:
    metadata:
      labels:
        app: test-echo-ip
    spec:
      containers:
      - name: test-echo-ip
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: test-echo-ip-config
          mountPath: /etc/nginx/conf.d
      volumes:
        - name: test-echo-ip-config
          configMap:
            name: test-echo-ip-config
