# Service / internal network ports

apiVersion: v1
kind: Service
metadata:
  name: bungee
  namespace: stage
  labels:
    app: bungee
spec:
  type: ClusterIP
  selector:
    app: bungee
  ports:
  - name: monumenta-socket
    port: 9576
    targetPort: 9576
  - name: plan
    port: 8804
    targetPort: 8804

---

# Service / external network ports

apiVersion: v1
kind: Service
metadata:
  name: bungee-nodeport
  namespace: stage
  labels:
    app: bungee
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: bungee
  ports:
  - name: minecraft
    port: 9002
    nodePort: 9002
    targetPort: 25566

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungee
  namespace: stage
  labels:
    app: bungee
spec:
  strategy:
    type: Recreate
  replicas: 0
  selector:
    matchLabels:
      app: bungee
  template:
    metadata:
      labels:
        app: bungee
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-11
      volumes:
        - name: nfs-volume
          hostPath:
            type: Directory
            path: /nfs/stage/project_epic
        - name: nfs-plan
          hostPath:
            type: Directory
            path: /nfs/stage/plan
      terminationGracePeriodSeconds: 90
      containers:
      - name: bungee
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-java-shard
        tty: true
        stdin: true
        ports:
        - containerPort: 25566
        - containerPort: 9575
        - containerPort: 8804
        env:
        - name: "JAVA_MEM"
          value: "512M"
        - name: "JAVA_META_MEM"
          value: "128M"
        - name: "JAVA_JAR"
          value: "BungeeCord.jar"
        - name: "SERVER_DIR"
          value: "/project_epic/bungee"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
        readinessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: nfs-volume
          mountPath: /project_epic
        - name: nfs-plan
          mountPath: /plan
        resources:
          limits:
            memory: 1Gi
            hugepages-2Mi: 704Mi
          requests:
            memory: 64Mi
            hugepages-2Mi: 704Mi
      imagePullSecrets:
      - name: githubcred
