# Service / network ports

apiVersion: v1
kind: Service
metadata:
  name: purgatory
  namespace: stage
  labels:
    app: purgatory
spec:
  type: ClusterIP
  selector:
    app: purgatory
  ports:
  # Main minecraft port
  - name: "25566"
    port: 25566
    targetPort: 25566

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: purgatory
  namespace: stage
  labels:
    app: purgatory
spec:
  strategy:
    type: Recreate
  replicas: 0
  selector:
    matchLabels:
      app: purgatory
  template:
    metadata:
      labels:
        app: purgatory
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - monumenta-8
      volumes:
        - name: nfs-volume
          hostPath:
            type: Directory
            path: /nfs/stage/project_epic
      containers:
      - name: purgatory
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-java-shard
        tty: true
        stdin: true
        ports:
        - containerPort: 25566
        env:
        - name: "JAVA_MEM"
          value: "256M"
        - name: "JAVA_META_MEM"
          value: "128M"
        - name: "JAVA_JAR"
          value: "paperclip.jar"
        - name: "SERVER_DIR"
          value: "/project_epic/purgatory"
        readinessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: nfs-volume
          mountPath: /project_epic
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
      imagePullSecrets:
      - name: githubcred
