# Service / network ports

apiVersion: v1
kind: Service
metadata:
  name: depths-3
  namespace: play
  labels:
    app: depths-3
    k8s-app: monumenta-metrics
spec:
  type: ClusterIP
  selector:
    app: depths-3
  ports:
  # Main minecraft port
  - name: "25566"
    port: 25566
    targetPort: 25566
  - name: plan
    port: 8804
    targetPort: 8804
  - name: metrics
    port: 9225
    targetPort: 9225

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: depths-3
  namespace: play
  labels:
    app: depths-3
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: depths-3
  template:
    metadata:
      labels:
        app: depths-3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-11
      volumes:
        - name: gsheet-credentials
          secret:
            secretName: gsheet-credentials
            defaultMode: 0444
        - name: nfs-maps
          hostPath:
            path: /nfs/play/maps
            type: Directory
        - name: nfs-play-m11
          hostPath:
            path: /nfs/play/m11
            type: Directory
        - name: nfs-shared
          hostPath:
            path: /nfs/4_SHARED
            type: Directory
      terminationGracePeriodSeconds: 90
      containers:
      - name: depths-3
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-java-shard
        tty: true
        stdin: true
        ports:
        - containerPort: 25566
        - containerPort: 8804
        - containerPort: 8000
        - containerPort: 9225
        env:
        # Set this to however much RAM the shard needs
        - name: "JAVA_MEM"
          value: "3G"
        # Set this to 256M regardless of JAVA_MEM
        - name: "JAVA_META_MEM"
          value: "256M"
        - name: "JAVA_JAR"
          value: "paperclip.jar"
        - name: "SERVER_DIR"
          value: "/home/epic/play/m11/depths-3"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /alive
            port: 8000
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: gsheet-credentials
          mountPath: /home/epic/play/m11/depths-3/plugins/ScriptedQuests/gsheet_credentials.json
          subPath: gsheet_credentials.json
        - name: nfs-play-m11
          mountPath: /home/epic/play/m11
        - name: nfs-maps
          mountPath: /home/epic/maps/dynmap/play
        - name: nfs-shared
          mountPath: /home/epic/4_SHARED
        resources:
          limits:
            # Set this to 1Gi
            # This is the hard limit for how much RAM a shard can allocate beyond what it needs for hugepages
            # It should not need much/any...
            memory: 1Gi
            # Set this to JAVA_MEM + JAVA_META_MEM + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: 3520Mi
          requests:
            # Set this to 64Mi
            # The shard should not need non-hugepage RAM by default
            memory: 64Mi
            # Set this to JAVA_MEM + JAVA_META_MEM + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: 3520Mi
      imagePullSecrets:
      - name: githubcred
