#
# NOTE:
# To generate the maps-auth secret, run these commands:
# htpasswd -c ./auth plan
# kubectl create secret generic plan-auth --from-file auth -n play
# rm auth
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plan
  namespace: play
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: plan-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - plan.playmonumenta.com
  rules:
  - host: plan.playmonumenta.com
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: bungee
              port:
                number: 8804

---

# Service / internal network ports

apiVersion: v1
kind: Service
metadata:
  name: bungee
  namespace: play
  labels:
    app: bungee
    k8s-app: monumenta-metrics
spec:
  type: ClusterIP
  selector:
    app: bungee
  ports:
  - name: plan
    port: 8804
    targetPort: 8804
  - name: metrics
    port: 9225
    targetPort: 9225

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungee
  namespace: play
  labels:
    app: bungee
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bungee
  template:
    metadata:
      labels:
        app: bungee
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-17
      volumes:
        - name: nfs-volume
          hostPath:
            path: /nfs/play/m17
            type: Directory
      containers:
      - name: bungee
        image: ghcr.io/teammonumenta/monumenta-automation/monumenta-java-shard-17
        tty: true
        stdin: true
        ports:
        # Primary Minecraft port
        - containerPort: 25566
          hostPort: 25565
          hostIP: "15.235.84.119" # The node's external facing IP address
        # Votifier
        - containerPort: 8192
          hostPort: 3333
          hostIP: "15.235.84.119" # The node's external facing IP address
        - containerPort: 9225
        env:
        - name: "JAVA_MEM"
          value: "4G"
        - name: "JAVA_META_MEM"
          value: "256M"
        - name: "JAVA_JAR"
          value: "BungeeCord.jar"
        - name: "SERVER_DIR"
          value: "/home/epic/play/m17/bungee"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
        - name: "JAVA_ARG"
          value: "-Dlog4j2.configurationFile=log4j2-bungee.xml"
        - name: "NETWORK_RELAY_NAME"
          value: bungee
        readinessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: nfs-volume
          mountPath: /home/epic/play/m17
        resources:
          limits:
            memory: 1Gi
            hugepages-2Mi: 4608Mi
          requests:
            memory: 64Mi
            hugepages-2Mi: 4608Mi
