# NOTE: This uses the same permissions as the automation-bot! If the automation bot is not set up, this will not work.

# This is the actual cron job, specifying what it should run
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-automated-restart
  namespace: play
  labels:
    app: cron-automated-restart
spec:
  schedule: "55 8 * * SUN,MON,TUE,WED,THU,SAT"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-automated-restart
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - monumenta-8
          serviceAccountName: automation-bot-service-account
          volumes:
          - name: secret-config
            secret:
              secretName: automation-bot-config
          - name: nfs-data
            hostPath:
              type: Directory
              path: /nfs/play/m8/bungee/plugins/BungeeDisplay
          containers:
          - name: cron-automated-restart
            image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-automation-bot
            tty: false
            stdin: false
            args:
            - /home/epic/MCEdit-And-Automation/utility_code/daily_restart.py
            volumeMounts:
            - name: secret-config
              mountPath: /home/epic/.monumenta_bot
            - name: nfs-data
              mountPath: /home/epic/play/m8/bungee/plugins/BungeeDisplay
          restartPolicy: Never
          imagePullSecrets:
          - name: githubcred
