apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: play
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: play
data:
  mysql.cnf: |
    [mysql]
    max_connections = 500
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
  mysqldump.cnf: |
    [mysqldump]
    quick
    quote-names
    max_allowed_packet      = 16M

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: play
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ns547336.ip-66-70-181.net
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # This secret was created using:
          #  kubectl create secret generic mysql-secret -n play --from-literal=username=root --from-literal=password='THE PASSWORD'
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            type: Directory
            path: /nfs/play/mysql
        - name: mysql-config
          configMap:
            name: mysql-config
