apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: play
spec:
  ports:
  - port: 5672
  selector:
    app: rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mgmt
  namespace: play
spec:
  ports:
  - port: 15672
  selector:
    app: rabbitmq-mgmt

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: play
spec:
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-17
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "monumenta-rabbit"
      containers:
      - image: rabbitmq:3.12-management
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: rabbitmq
        - containerPort: 15672
          name: rabbitmq-mgmt
        volumeMounts:
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/conf.d/20-monumenta-custom.conf
          subPath: 20-monumenta-custom.conf
        resources:
          limits:
            memory: 2Gi
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: play
data:
  20-monumenta-custom.conf: |
    ## Busty: This config file was derived from
    ## https://github.com/rabbitmq/rabbitmq-server/blob/v3.12.x/deps/rabbit/docs/rabbitmq.conf.example

    ##
    ## Resource Limits & Flow Control
    ## ==============================
    ##
    ## Related doc guide: https://rabbitmq.com/memory.html.
    vm_memory_high_watermark.absolute = 768M

    ## usb: Default limit is very low (128) https://www.rabbitmq.com/docs/networking#tuning-for-large-number-of-connections-connection-backlog
    tcp_listen_options.backlog = 256
