# The nodeport service exposing the SSH port

apiVersion: v1
kind: Service
metadata:
  name: eu-ssh-nodeport
  namespace: clash
  labels:
    app: eu-ssh
spec:
  type: NodePort
  selector:
    app: eu-ssh
  ports:
  # SSH
  - name: "22"
    port: 22
    nodePort: 20023
    targetPort: 22

---

# The actual container that runs SSH that you can connect to

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eu-ssh
  namespace: clash
  labels:
    app: eu-ssh
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: eu-ssh
  template:
    metadata:
      labels:
        app: eu-ssh
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-10
      volumes:
        - name: nfs-data
          hostPath:
            type: Directory
            path: /nfs/clash
        - name: authorized-keys-config
          secret:
            secretName: authorized-keys-config
            defaultMode: 292
      containers:
      - name: eu-ssh
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-basic-ssh
        tty: false
        stdin: false
        ports:
        - containerPort: 22
        volumeMounts:
        - name: nfs-data
          mountPath: /home/epic/clash
        - name: authorized-keys-config
          mountPath: /home/epic/.ssh/authorized_keys
          subPath: authorized_keys
      imagePullSecrets:
      - name: githubcred
