
# k port-forward -n stage deployment/adminer 9999:8080
# ssh admin -L 9999:127.0.0.1:9999

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: stage
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-8
      containers:
        - name: adminer
          image: adminer:4.6.3
          ports:
            - containerPort: 8080
