# Service / internal network ports (for loading play data)

apiVersion: v1
kind: Service
metadata:
  name: automation-bot-m17
  namespace: stage
  labels:
    app: automation-bot-m17
spec:
  selector:
    app: automation-bot-m17
  ports:
  - name: stage1
    port: 1111
    targetPort: 1111
  - name: stage2
    port: 1112
    targetPort: 1112
  - name: stage3
    port: 1113
    targetPort: 1113
  - name: stage4
    port: 1114
    targetPort: 1114
  - name: stage5
    port: 1115
    targetPort: 1115

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-bot-m17
  namespace: stage
  labels:
    app: automation-bot-m17
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: automation-bot-m17
  template:
    metadata:
      labels:
        app: automation-bot-m17
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-17
      serviceAccountName: automation-bot-service-account
      volumes:
        - name: nfs-data
          hostPath:
            type: Directory
            path: /nfs/stage/m17
        - name: nfs-domain-shared
          hostPath:
            type: Directory
            path: /nfs/3_DOMAIN_SHARED/stage
        - name: nfs-shared
          hostPath:
            type: Directory
            path: /nfs/4_SHARED
        - name: nfs-scratch
          hostPath:
            type: Directory
            path: /nfs/5_SCRATCH
        - name: secret-config
          secret:
            secretName: automation-bot-m17-config
      containers:
      - name: automation-bot
        image: ghcr.io/teammonumenta/monumenta-automation/monumenta-automation-bot-stage
        tty: false
        stdin: false
        ports:
        - containerPort: 1111
        - containerPort: 1112
        - containerPort: 1113
        - containerPort: 1114
        - containerPort: 1115
        env:
          # This is the root password in a convenient environment variable so it can be used to copy the mysql
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - name: nfs-data
          mountPath: /home/epic/stage/m17
        - name: nfs-domain-shared
          mountPath: /home/epic/3_DOMAIN_SHARED
        - name: nfs-shared
          mountPath: /home/epic/4_SHARED
        - name: nfs-scratch
          mountPath: /home/epic/5_SCRATCH
        - name: secret-config
          mountPath: /home/epic/.monumenta_bot
        resources:
          requests:
            cpu: "0"
          limits:
            cpu: "12"
      imagePullSecrets:
      - name: githubcred
