# Service / internal network ports

apiVersion: v1
kind: Service
metadata:
  name: bungee
  namespace: stage
  labels:
    app: bungee
    k8s-app: monumenta-metrics
spec:
  type: ClusterIP
  selector:
    app: bungee
  ports:
  - name: plan
    port: 8804
    targetPort: 8804
  - name: metrics
    port: 9225
    targetPort: 9225

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungee
  namespace: stage
  labels:
    app: bungee
spec:
  strategy:
    type: Recreate
  replicas: 0
  selector:
    matchLabels:
      app: bungee
  template:
    metadata:
      labels:
        app: bungee
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-13
      volumes:
        - name: nfs-volume
          hostPath:
            path: /nfs/stage/m13
            type: Directory
      containers:
      - name: bungee
        image: ghcr.io/teammonumenta/monumenta-automation/monumenta-java-shard-17
        tty: true
        stdin: true
        ports:
        # Primary Minecraft port
        - containerPort: 25566
          hostPort: 9002
          hostIP: "15.235.54.193" # The node's external facing IP address
        # Votifier
        - containerPort: 8192
          hostPort: 23333
          hostIP: "15.235.54.193" # The node's external facing IP address
        - containerPort: 8804
        - containerPort: 9225
        env:
        - name: "JAVA_MEM"
          value: "512M"
        - name: "JAVA_META_MEM"
          value: "128M"
        - name: "JAVA_JAR"
          value: "BungeeCord.jar"
        - name: "SERVER_DIR"
          value: "/home/epic/stage/m13/bungee"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
        - name: "NETWORK_RELAY_NAME"
          value: bungee
        readinessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: nfs-volume
          mountPath: /home/epic/stage/m13
        resources:
          limits:
            memory: 1Gi
            hugepages-2Mi: 704Mi
          requests:
            memory: 64Mi
            hugepages-2Mi: 704Mi
