# This is the actual cron job, specifying what it should run
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-automated-restart
  namespace: stage
  labels:
    app: cron-automated-restart
spec:
  schedule: "55 6 * * SUN,MON,TUE,WED,THU,FRI,SAT"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-automated-restart
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - monumenta-12
          serviceAccountName: automation-bot-service-account
          volumes:
          - name: secret-config
            secret:
              secretName: automated-restart
          - name: nfs-data
            hostPath:
              type: Directory
              path: /nfs/stage/m12/bungee/plugins/BungeeDisplay
          - name: nfs-data-11
            hostPath:
              type: Directory
              path: /nfs/play/m12/bungee-11/plugins/BungeeDisplay
          - name: nfs-data-13
            hostPath:
              type: Directory
              path: /nfs/play/m12/bungee-13/plugins/BungeeDisplay
          containers:
          - name: cron-automated-restart
            image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-automation-bot
            tty: false
            stdin: false
            args:
            - /home/epic/MCEdit-And-Automation/utility_code/daily_restart.py
            volumeMounts:
            - name: secret-config
              mountPath: /home/epic/.monumenta_bot
            - name: nfs-data
              mountPath: /home/epic/stage/m12/bungee/plugins/BungeeDisplay
            - name: nfs-data-11
              mountPath: /home/epic/stage/m12/bungee-11/plugins/BungeeDisplay
            - name: nfs-data-13
              mountPath: /home/epic/stage/m12/bungee-13/plugins/BungeeDisplay
          restartPolicy: Never
          imagePullSecrets:
          - name: githubcred
