# Service / network ports

apiVersion: v1
kind: Service
metadata:
  name: fire-nodeport
  namespace: external
  labels:
    app: fire
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: fire
  ports:
  - name: minecraft
    port: 5565
    nodePort: 5565
    targetPort: 25566
  - name: dynmap
    port: 5566
    nodePort: 5566
    targetPort: 8123

---

# Deployment / the actual running application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fire
  namespace: external
  labels:
    app: fire
spec:
  strategy:
    type: Recreate
  replicas: 0
  selector:
    matchLabels:
      app: fire
  template:
    metadata:
      labels:
        app: fire
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-9
      volumes:
        - name: nfs-external
          hostPath:
            type: Directory
            path: /nfs/external
      containers:
      - name: fire
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-java-shard
        tty: true
        stdin: true
        ports:
        - containerPort: 25566
        env:
        # Set this to however much RAM the shard needs
        - name: "JAVA_MEM"
          value: "2G"
        # Set this to 256M regardless of JAVA_MEM
        - name: "JAVA_META_MEM"
          value: "256M"
        - name: "JAVA_JAR"
          value: "paperclip.jar"
        - name: "SERVER_DIR"
          value: "/external/fire"
        - name: "JAVA_LARGE_PAGES"
          value: "yes"
        readinessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 25566
          initialDelaySeconds: 240
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: nfs-external
          mountPath: /external
        resources:
          limits:
            # Set this to 1Gi
            # This is the hard limit for how much RAM a shard can allocate beyond what it needs for hugepages
            # It should not need much/any...
            memory: 1Gi
            # Set this to JAVA_MEM + JAVA_META_MEM + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: 2432Mi
          requests:
            # Set this to 64Mi
            # The shard should not need non-hugepage RAM by default
            memory: 64Mi
            # Set this to JAVA_MEM + JAVA_META_MEM + 64 per gigabyte of JAVA_MEM
            hugepages-2Mi: 2432Mi
      imagePullSecrets:
      - name: githubcred
