#!/usr/bin/env python3

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__),'..'))

from lib.item_test import ItemTest

test_item = ItemTest(
    test_name="Rules: 1.16 Upgrade: Plain Tag: Light of Salvation",
    template_item=r'''{id:"minecraft:golden_sword", tag: {Enchantments:[{id:"minecraft:efficiency",lvl:2s},{id:"minecraft:fire_aspect",lvl:1s},{id:"minecraft:knockback",lvl:1s}],Unbreakable:1b,Damage:0,HideFlags:2,plain:{display:{Name:"Light of Salvation",Lore:["Radiant","Hope","King's Valley : Artifact","Arena of Terth","A memory of light, long gone.","","When in Main Hand:","1.6 Attack Speed","3 Attack Damage"]}},AttributeModifiers:[{Name:"Modifier",Amount:0.0d,Operation:0,UUID:[I;252418896,-41007586,-1588948211,264260124],AttributeName:"minecraft:generic.attack_damage"},{Name:"Modifier",Amount:-2.4d,Operation:0,UUID:[I;591187793,-1381675297,-1856321554,-1055512585],Slot:"mainhand",AttributeName:"minecraft:generic.attack_speed"},{Name:"Modifier",Amount:2.0d,Operation:0,UUID:[I;1414638480,94455665,-1760832458,914145374],Slot:"mainhand",AttributeName:"minecraft:generic.attack_damage"}],display:{Name:'{"extra":[{"bold":true,"italic":false,"underlined":true,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Light of Salvation"}],"text":""}',Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Radiant"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Hope"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"King\'s Valley : "},{"italic":false,"color":"dark_red","text":"Artifact"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Arena of Terth"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"A memory of light, long gone."}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"When in Main Hand:"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":" 1.6 Attack Speed"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":" 3 Attack Damage"}],"text":""}']}}, Count: 1b}''',
    item_under_test=r'''{id: "minecraft:golden_sword", tag: {Damage: 0, display: {Name: '"Light of Salvation"', Lore: ['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Radiant"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Hope"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"King\'s Valley : "},{"italic":false,"color":"dark_red","text":"Artifact"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Arena of Terth"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"A memory of light, long gone."}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"When in Main Hand:"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":" 1.6 Attack Speed"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":" 3 Attack Damage"}],"text":""}','{"text":"* Soulbound to NickNackGus *"}']}}, Count: 1b}''',
    expected_result_item=r'''{id: "minecraft:golden_sword", tag: {Enchantments:[{id:"minecraft:efficiency",lvl:2s},{id:"minecraft:fire_aspect",lvl:1s},{id:"minecraft:knockback",lvl:1s}],Unbreakable:1b,Damage:0,HideFlags:2,plain:{display:{Name:"Light of Salvation",Lore:["Radiant","Hope","King's Valley : Artifact","Arena of Terth","A memory of light, long gone.","","When in Main Hand:","1.6 Attack Speed","3 Attack Damage","* Soulbound to NickNackGus *"]}},AttributeModifiers:[{Name:"Modifier",Amount:0.0d,Operation:0,UUID:[I;252418896,-41007586,-1588948211,264260124],AttributeName:"minecraft:generic.attack_damage"},{Name:"Modifier",Amount:-2.4d,Operation:0,UUID:[I;591187793,-1381675297,-1856321554,-1055512585],Slot:"mainhand",AttributeName:"minecraft:generic.attack_speed"},{Name:"Modifier",Amount:2.0d,Operation:0,UUID:[I;1414638480,94455665,-1760832458,914145374],Slot:"mainhand",AttributeName:"minecraft:generic.attack_damage"}],display:{Name:'{"extra":[{"bold":true,"italic":false,"underlined":true,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Light of Salvation"}],"text":""}',Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Radiant"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Hope"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"King\'s Valley : "},{"italic":false,"color":"dark_red","text":"Artifact"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Arena of Terth"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"A memory of light, long gone."}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"When in Main Hand:"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":" 1.6 Attack Speed"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":" 3 Attack Damage"}],"text":""}','{"text":"* Soulbound to NickNackGus *"}']}}, Count: 1b}'''
)
test_item.run()

