#!/usr/bin/env python3

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__),'..'))

from lib.item_test import ItemTest

test_item = ItemTest(
    test_name="Rules: 1.16 Upgrade: Totem of Transposing",
    template_item=r'''{id:"minecraft:ender_eye",tag:{display:{Name:'{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","extra":[{"text":"Totem of Transposing"}],"text":""}',Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Celsian Isles : "},{"italic":false,"color":"dark_purple","text":"Unique"}],"text":""}','{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","extra":[{"text":"Transposing Channel: ID MISSING"}],"text":""}','{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","extra":[{"keybind":"key.use"},{"text":" while in main hand"}],"text":""}','{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","extra":[{"text":" to swap places with your partner."}],"text":""}']},plain:{display:{Name:"Totem of Transposing",Lore:["Celsian Isles : Unique","Transposing Channel: ID MISSING","key.use while in main hand","to swap places with your partner."]}}},Count:2b}''',
    item_under_test=r'''{id: "minecraft:ender_eye", tag: {display: {Name: '{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","extra":[{"text":"Totem of Transposing"}],"text":""}', Lore: ['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Celsian Isles : "},{"italic":false,"color":"dark_purple","text":"Unique"}],"text":""}', '{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","extra":[{"text":"Transposing Channel: "},{"text":"25"}],"text":""}', '{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","extra":[{"keybind":"key.use"},{"text":" while in main hand"}],"text":""}', '{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","extra":[{"text":" to swap places with your partner."}],"text":""}']}, plain: {display: {Name: "Totem of Transposing", Lore: ["Celsian Isles : Unique", "Transposing Channel: 25"]}}, TransposingID: 25}, Count: 1b}''',
    expected_result_item=r'''{id: "minecraft:ender_eye", tag: {display: {Name: '{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","extra":[{"text":"Totem of Transposing"}],"text":""}', Lore: ['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Celsian Isles : "},{"italic":false,"color":"dark_purple","text":"Unique"}],"text":""}', '{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","extra":[{"text":"Transposing Channel: "},{"text":"25"}],"text":""}', '{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","extra":[{"keybind":"key.use"},{"text":" while in main hand"}],"text":""}', '{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","extra":[{"text":" to swap places with your partner."}],"text":""}']}, plain: {display: {Name: "Totem of Transposing", Lore: ["Celsian Isles : Unique", "Transposing Channel: 25", "key.use while in main hand", "to swap places with your partner."]}}, TransposingID: 25}, Count: 1b}'''
)
test_item.run()
