
# This is a service account for the bot's pod to use to talk to the controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: automation-bot-service-account
  namespace: external

---

# This is the permission object that will be attached to the above service account
# This specifies what the pod is allowed to do
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: automation-bot-role
  namespace: external
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - deployments
    verbs:
      - list
      - patch

---

# This binds the role to the service account, giving it perms
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: automation-bot-role-binding
  namespace: external
roleRef:
  kind: Role
  name: automation-bot-role
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: automation-bot-service-account
   namespace: external

---

# This is the actual bot's deployment, specifying what it should run
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-bot
  namespace: external
  labels:
    app: automation-bot
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: automation-bot
  template:
    metadata:
      labels:
        app: automation-bot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - monumenta-11
      serviceAccountName: automation-bot-service-account
      volumes:
        - name: secret-config
          secret:
            secretName: automation-bot-config
      containers:
      - name: automation-bot
        image: docker.pkg.github.com/teammonumenta/monumenta-automation/monumenta-automation-bot
        tty: false
        stdin: false
        volumeMounts:
        - name: secret-config
          mountPath: /home/epic/.monumenta_bot
        resources:
          limits:
            cpu: "0.2"
      imagePullSecrets:
      - name: githubcred
