name: monumenta-sdk
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.12-management
        networks:
            - sdk-network
        restart: unless-stopped
        volumes:
            - ./rabbitmq.conf:/etc/rabbitmq/conf.d/20-monumenta-custom.conf
    redis:
        container_name: redis
        image: redis:7.4.0
        networks:
            - sdk-network
        restart: unless-stopped
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        user: "${UID}:${GID}"
    velocity:
        container_name: velocity
        image: ghcr.io/teammonumenta/monumenta-automation/monumenta-java-jbr-shard-21
        depends_on:
            - redis
            - rabbitmq
        networks:
            - sdk-network
        restart: unless-stopped
        volumes:
            - .:/home/epic/sdk
        environment:
            JAVA_MEM: 1G
            JAVA_JAR: velocity.jar
            SERVER_DIR: /home/epic/sdk/velocity/
            JAVA_ARG: -Dlog4j2.configurationFile=log4j2-velocity.xml
            NETWORK_RELAY_NAME: velocity
            ALLOW_PACKETS_PUBLICIZE_CONTENT: true
        user: "${UID}:${GID}"
    sdk1:
        container_name: sdk1
        image: ghcr.io/teammonumenta/monumenta-automation/monumenta-java-jbr-shard-21
        depends_on:
            - redis
            - rabbitmq
        networks:
            - sdk-network
        restart: unless-stopped
        volumes:
            - .:/home/epic/sdk
        environment:
            JAVA_MEM: 2G
            JAVA_JAR: server.jar
            SERVER_DIR: /home/epic/sdk/sdk1/
            NETWORK_NAMESPACE: build
            NETWORK_RELAY_NAME: sdk1
            JAVA_ARG: -DPaper.IgnoreJavaVersion=true -Ddisable.watchdog -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000 -Dlog4j2.configurationFile=log4j2-shard.xml -XX:+AllowEnhancedClassRedefinition
        user: "${UID}:${GID}"
    sdk2:
        container_name: sdk2
        image: ghcr.io/teammonumenta/monumenta-automation/monumenta-java-jbr-shard-21
        depends_on:
            - redis
            - rabbitmq
        networks:
            - sdk-network
        restart: unless-stopped
        volumes:
            - .:/home/epic/sdk
        environment:
            JAVA_MEM: 2G
            JAVA_JAR: server.jar
            SERVER_DIR: /home/epic/sdk/sdk2/
            NETWORK_NAMESPACE: build
            NETWORK_RELAY_NAME: sdk2
            JAVA_ARG: -DPaper.IgnoreJavaVersion=true -Ddisable.watchdog -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000 -Dlog4j2.configurationFile=log4j2-shard.xml -XX:+AllowEnhancedClassRedefinition
        user: "${UID}:${GID}"
networks:
    sdk-network:
