name: Build and publish master
# This is a common script, so we only listen to workflow_call
on: 
  workflow_call:
    secrets:
      MAVEN_TOKEN:
        required: true
# Jobs
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Set up JDK, we might want to bump this to Java 21
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: zulu # See 'Supported distributions' for available options
        java-version: "17"
    # Git config, not sure why this is needed?
    - name: git config
      run: |
          git config --global user.name "Monumenta CI"
          git config --global user.email "Monumenta.CI@NotARealEmail.com"
    # Cache dependencies so we don't have to download them every run
    - name: Cache maven dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-maven-dependencies
      with:
        # maven files are stored in `~/.m2/repository`
        path: |
          ~/.m2/repository
          ~/.gradle/caches
          ~/.gradle/wrapper
        # Create the key based on runner os, cache name, and a hash of all the pom.xml files
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Run publishing
    - name: Publish to Monumenta Maven
      env:
        USERNAME: monumenta
        TOKEN: ${{ secrets.MAVEN_TOKEN }}
      run: |
        ./gradlew publish
