name: Reviewdog checks 
# This is a common script, so we only listen to workflow_call
on: [workflow_call]
# Jobs
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    # Set up JDK, we might want to bump this to Java 21
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
        check-latest: true
    # Reviewdog
    - name: Setup reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    # Git config, not sure why this is needed?
    - name: Apply global CI config
      run: |
        git config --global user.name "Monumenta CI"
        git config --global user.email "Monumenta.CI@NotARealEmail.com"
    # Cache dependencies so we don't have to download them every run
    - name: Cache maven dependencies
      uses: actions/cache@v4
      env:
        cache-name: cache-maven-dependencies
      with:
        # maven files are stored in `~/.m2/repository`
        path: |
          ~/.m2/repository
          ~/.gradle/caches
          ~/.gradle/wrapper
        # Create the key based on runner os, cache name, and a hash of all the pom.xml files
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Reviewdog stuff...
    - name: Build and report style/pmd/warnings
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        shopt -s nullglob
        set -o pipefail
        ./gradlew build --console=plain 2>&1 | tee compile.log
        set +o pipefail
        cat compile.log | reviewdog -efm="%W%f:%l: warning: %m" -efm="%+C%[ %\t]%.%#" -name="compiler-warnings" -level=error -fail-on-error -reporter=github-pr-review
        cat */build/reports/pmd/main.xml build/reports/pmd/main.xml | reviewdog -efm='%+P<file name="%f">' -efm='%W<violation beginline="%l%.%#begincolumn="%c%.%#' -efm='%-C<%.%#' -efm='%+C%.%#' -efm='%-Q' -name="pmd" -level=error -fail-on-error -reporter=github-pr-review
        cat */build/reports/checkstyle/main.xml build/reports/checkstyle/main.xml | reviewdog -f=checkstyle -name="checkstyle" -level=error -fail-on-error -reporter=github-pr-review
